<?php

namespace ContainerWX4I3io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NBDTncIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NBDTncI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NBDTncI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CompanyController::delete' => ['privates', '.service_locator.yJ_47WL', 'get_ServiceLocator_YJ47WLService', true],
            'App\\Controller\\CompanyController::edit' => ['privates', '.service_locator.yJ_47WL', 'get_ServiceLocator_YJ47WLService', true],
            'App\\Controller\\CompanyController::index' => ['privates', '.service_locator.cxUIR7o', 'get_ServiceLocator_CxUIR7oService', true],
            'App\\Controller\\CompanyController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CompanyController::show' => ['privates', '.service_locator.9wNU0CU', 'get_ServiceLocator_9wNU0CUService', true],
            'App\\Controller\\ResumeController::delete' => ['privates', '.service_locator.2R4rHS6', 'get_ServiceLocator_2R4rHS6Service', true],
            'App\\Controller\\ResumeController::edit' => ['privates', '.service_locator.2R4rHS6', 'get_ServiceLocator_2R4rHS6Service', true],
            'App\\Controller\\ResumeController::index' => ['privates', '.service_locator.gBJ0DM4', 'get_ServiceLocator_GBJ0DM4Service', true],
            'App\\Controller\\ResumeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ResumeController::show' => ['privates', '.service_locator.LsXnsId', 'get_ServiceLocator_LsXnsIdService', true],
            'App\\Controller\\ResumeSubmissionController::delete' => ['privates', '.service_locator.xtvkGli', 'get_ServiceLocator_XtvkGliService', true],
            'App\\Controller\\ResumeSubmissionController::edit' => ['privates', '.service_locator.xtvkGli', 'get_ServiceLocator_XtvkGliService', true],
            'App\\Controller\\ResumeSubmissionController::index' => ['privates', '.service_locator.ZRLjgtM', 'get_ServiceLocator_ZRLjgtMService', true],
            'App\\Controller\\ResumeSubmissionController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ResumeSubmissionController::show' => ['privates', '.service_locator.bWNVHx.', 'get_ServiceLocator_BWNVHx_Service', true],
            'App\\Controller\\StatisticsController::index' => ['privates', '.service_locator..grl7L4', 'get_ServiceLocator__Grl7L4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CompanyController:delete' => ['privates', '.service_locator.yJ_47WL', 'get_ServiceLocator_YJ47WLService', true],
            'App\\Controller\\CompanyController:edit' => ['privates', '.service_locator.yJ_47WL', 'get_ServiceLocator_YJ47WLService', true],
            'App\\Controller\\CompanyController:index' => ['privates', '.service_locator.cxUIR7o', 'get_ServiceLocator_CxUIR7oService', true],
            'App\\Controller\\CompanyController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CompanyController:show' => ['privates', '.service_locator.9wNU0CU', 'get_ServiceLocator_9wNU0CUService', true],
            'App\\Controller\\ResumeController:delete' => ['privates', '.service_locator.2R4rHS6', 'get_ServiceLocator_2R4rHS6Service', true],
            'App\\Controller\\ResumeController:edit' => ['privates', '.service_locator.2R4rHS6', 'get_ServiceLocator_2R4rHS6Service', true],
            'App\\Controller\\ResumeController:index' => ['privates', '.service_locator.gBJ0DM4', 'get_ServiceLocator_GBJ0DM4Service', true],
            'App\\Controller\\ResumeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ResumeController:show' => ['privates', '.service_locator.LsXnsId', 'get_ServiceLocator_LsXnsIdService', true],
            'App\\Controller\\ResumeSubmissionController:delete' => ['privates', '.service_locator.xtvkGli', 'get_ServiceLocator_XtvkGliService', true],
            'App\\Controller\\ResumeSubmissionController:edit' => ['privates', '.service_locator.xtvkGli', 'get_ServiceLocator_XtvkGliService', true],
            'App\\Controller\\ResumeSubmissionController:index' => ['privates', '.service_locator.ZRLjgtM', 'get_ServiceLocator_ZRLjgtMService', true],
            'App\\Controller\\ResumeSubmissionController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ResumeSubmissionController:show' => ['privates', '.service_locator.bWNVHx.', 'get_ServiceLocator_BWNVHx_Service', true],
            'App\\Controller\\StatisticsController:index' => ['privates', '.service_locator..grl7L4', 'get_ServiceLocator__Grl7L4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CompanyController::delete' => '?',
            'App\\Controller\\CompanyController::edit' => '?',
            'App\\Controller\\CompanyController::index' => '?',
            'App\\Controller\\CompanyController::new' => '?',
            'App\\Controller\\CompanyController::show' => '?',
            'App\\Controller\\ResumeController::delete' => '?',
            'App\\Controller\\ResumeController::edit' => '?',
            'App\\Controller\\ResumeController::index' => '?',
            'App\\Controller\\ResumeController::new' => '?',
            'App\\Controller\\ResumeController::show' => '?',
            'App\\Controller\\ResumeSubmissionController::delete' => '?',
            'App\\Controller\\ResumeSubmissionController::edit' => '?',
            'App\\Controller\\ResumeSubmissionController::index' => '?',
            'App\\Controller\\ResumeSubmissionController::new' => '?',
            'App\\Controller\\ResumeSubmissionController::show' => '?',
            'App\\Controller\\StatisticsController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CompanyController:delete' => '?',
            'App\\Controller\\CompanyController:edit' => '?',
            'App\\Controller\\CompanyController:index' => '?',
            'App\\Controller\\CompanyController:new' => '?',
            'App\\Controller\\CompanyController:show' => '?',
            'App\\Controller\\ResumeController:delete' => '?',
            'App\\Controller\\ResumeController:edit' => '?',
            'App\\Controller\\ResumeController:index' => '?',
            'App\\Controller\\ResumeController:new' => '?',
            'App\\Controller\\ResumeController:show' => '?',
            'App\\Controller\\ResumeSubmissionController:delete' => '?',
            'App\\Controller\\ResumeSubmissionController:edit' => '?',
            'App\\Controller\\ResumeSubmissionController:index' => '?',
            'App\\Controller\\ResumeSubmissionController:new' => '?',
            'App\\Controller\\ResumeSubmissionController:show' => '?',
            'App\\Controller\\StatisticsController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
