<?php

namespace ContainerWX4I3io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Grl7L4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..grl7L4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..grl7L4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'submissionRepository' => ['privates', 'App\\Repository\\ResumeSubmissionRepository', 'getResumeSubmissionRepositoryService', true],
        ], [
            'submissionRepository' => 'App\\Repository\\ResumeSubmissionRepository',
        ]);
    }
}
