<?php

namespace ContainerWX4I3io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GBJ0DM4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gBJ0DM4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gBJ0DM4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'resumeRepository' => ['privates', 'App\\Repository\\ResumeRepository', 'getResumeRepositoryService', true],
        ], [
            'resumeRepository' => 'App\\Repository\\ResumeRepository',
        ]);
    }
}
