<?php

namespace ContainerWX4I3io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResumeSubmissionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ResumeSubmissionType' shared autowired service.
     *
     * @return \App\Form\ResumeSubmissionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ResumeSubmissionType.php';

        return $container->privates['App\\Form\\ResumeSubmissionType'] = new \App\Form\ResumeSubmissionType();
    }
}
