<?php

namespace ContainerWX4I3io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StatisticsController' shared autowired service.
     *
     * @return \App\Controller\StatisticsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StatisticsController.php';

        $container->services['App\\Controller\\StatisticsController'] = $instance = new \App\Controller\StatisticsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\StatisticsController', $container));

        return $instance;
    }
}
