<?php

namespace ContainerRWLOnV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2R4rHS6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2R4rHS6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2R4rHS6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'resume' => ['privates', '.errored..service_locator.2R4rHS6.App\\Entity\\Resume', NULL, 'Cannot autowire service ".service_locator.2R4rHS6": it needs an instance of "App\\Entity\\Resume" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'resume' => 'App\\Entity\\Resume',
        ]);
    }
}
