<?php

namespace ContainerRWLOnV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResumeSubmission2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xtvkGli.App\Entity\ResumeSubmission' shared service.
     *
     * @return \App\Entity\ResumeSubmission
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xtvkGli": it needs an instance of "App\\Entity\\ResumeSubmission" but this type has been excluded in "config/services.yaml".');
    }
}
