<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWX4I3io\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWX4I3io/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWX4I3io.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWX4I3io\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWX4I3io\App_KernelDevDebugContainer([
    'container.build_hash' => 'WX4I3io',
    'container.build_id' => '87b31ea1',
    'container.build_time' => 1720432966,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWX4I3io');
